# Generated by Django 4.1 on 2022-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mairie', '0002_alter_album_description_alter_avis_texte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Une_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('titre', models.CharField(blank=True, max_length=250, null=True)),
                ('texte', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
