# Generated by Django 4.1 on 2022-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mairie', '0005_bureau_municipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('mail', models.EmailField(blank=True, max_length=200, null=True)),
                ('tel', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.CharField(blank=True, choices=[('Copie intégrale extrait de naissance', 'Copie intégrale extrait de naissance'), ('Extrait de naissance', 'Extrait de naissance'), ('Certificat de mariage', 'Certificat de mariage')], max_length=200, null=True)),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='')),
                ('adresse', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
